[package]
name = "xflow-platform"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = ["native-audio"]
native-audio = ["dep:cpal"]

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
serde_json.workspace = true
tokio.workspace = true
xflow-core = { path = "../xflow-core" }
cpal = { version = "0.15.3", optional = true }
zbus = { version = "4.4", default-features = false, features = ["tokio"] }
